### ISSUE TITLE
ログイン失敗時のエラーメッセージを変えたい

### ISSUE THREAD

**Issue by jkatagi** [takaiyuk/scrape-king-of-time#18]
## 現象
- ログインに失敗すると以下のエラーが表示されます
  - `error occurred: 'NoneType' object has no attribute 'string'`
- これは BeautifulSoupが本文をparseする時に、ログイン失敗画面をparseしてしまい、結果として存在しないtagをparseしてしまう（`self.soup.find("div", class_="work_count").string`） ためです

## 改善したいこと
- ログイン失敗時には「ログインに失敗しました」という旨のメッセージを表示させたいです

**Comment by takaiyuk** [comment]
エラー処理は全て握り潰す実装になっているので必要ですね

**Comment by takaiyuk** [comment]
`Exception: login failed` を表示するようにした
