### ISSUE TITLE
半休とった場合に集計が合わない

### ISSUE THREAD

**Issue by rikusouda** [takaiyuk/scrape-king-of-time#36]
# King of timeの状態
<img width="1327" alt="スクリーンショット 2019-11-19 13 06 40" src="https://user-images.githubusercontent.com/25785565/69115859-8b4eeb80-0acd-11ea-8a2e-295d34f5b81b.png">

# 実行結果
```
    残り10営業日: (10/20 日)

    あと74.59h必要: (85.01/160h)

    貯金: 5.01h

    貯金を元に残り営業日の必要勤務時間数を算出すると: 7.30h

    2019-11-19の出勤・定時
        出勤: 09:45
        定時: 18:45
```

平日: 9.5
有給 1.5
なので残り 9営業日になるのが正しい
(実際は借金が2.99hと思われる)

# 補足
scraper.pyの `_str_to_int` で整数型にしているためと思われる

**Comment by takaiyuk** [comment]
多分大丈夫

**Comment by rikusouda** [comment]
完璧感あります。超感謝です
