### ISSUE TITLE
貯金の表示型式にmを追加する

### ISSUE THREAD

**Issue by jkatagi** [takaiyuk/scrape-king-of-time#52]
## 背景
- 現状は貯金時間が x.xx h の型式になっている（例 0.5h)
- しかし上記例の0.5hだと0.5 * 60 min = 30 min なのか、 5 minなのかパット見わからない
  - 実際は後者

## リクエスト
- 小数点以下の表記をminであることを明記したい
- 例：1時間30分
  - Before: 1.30h
  - After: 1h30m

**Comment by takaiyuk** [comment]
👍

**Comment by takaiyuk** [comment]
表記変えたけどバグ混入
https://github.com/takaiyuk/scrape-king-of-time/pull/53

**Comment by takaiyuk** [comment]
#58
